# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOPsKt9XjztHMuiI3m3F-rdYUzLZWVnH
"""

angka = int(input('masukan angka:'))

for i in range (angka):
  if angka % 2 == 1:
    print(angka)
  angka = angka -1