# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOPsKt9XjztHMuiI3m3F-rdYUzLZWVnH
"""

teks = str(input('Masukan tesk: '))

for karakter in teks:
  if karakter == 'a' or karakter == 'A':
    print(karakter, end='')
  elif karakter == 'e' or karakter == 'E':
    print(karakter, end='')
  elif karakter == 'i' or karakter == 'I':
    print(karakter, end='')
  elif karakter == 'u' or karakter == 'U':
    print(karakter, end='')
  elif karakter == 'o' or karakter == 'O':
    print(karakter, end='')